/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.blockchain_innovation.factom.rosetta.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import javax.validation.Valid;
import org.blockchain_innovation.factom.rosetta.model.ConstructionCombineRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionCombineResponse;
import org.blockchain_innovation.factom.rosetta.model.ConstructionDeriveRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionDeriveResponse;
import org.blockchain_innovation.factom.rosetta.model.ConstructionHashRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionMetadataRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionMetadataResponse;
import org.blockchain_innovation.factom.rosetta.model.ConstructionParseRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionParseResponse;
import org.blockchain_innovation.factom.rosetta.model.ConstructionPayloadsRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionPayloadsResponse;
import org.blockchain_innovation.factom.rosetta.model.ConstructionPreprocessRequest;
import org.blockchain_innovation.factom.rosetta.model.ConstructionPreprocessResponse;
import org.blockchain_innovation.factom.rosetta.model.ConstructionSubmitRequest;
import org.blockchain_innovation.factom.rosetta.model.Error;
import org.blockchain_innovation.factom.rosetta.model.TransactionIdentifierResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-11T02:27:54.801Z[GMT]")
@Validated
public interface ConstructionApi {

    @Operation(summary = "Create Network Transaction from Signatures", description = "Combine creates a network-specific transaction from an unsigned transaction and an array of provided signatures. The signed transaction returned from this method will be sent to the `/construction/submit` endpoint by the caller.", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = ConstructionCombineResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/combine",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConstructionCombineResponse> constructionCombine(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionCombineRequest body);


    @Operation(summary = "Derive an AccountIdentifier from a PublicKey", description = "Derive returns the AccountIdentifier associated with a public key. Blockchains that require an on-chain action to create an account should not implement this method.", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = ConstructionDeriveResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/derive",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConstructionDeriveResponse> constructionDerive(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionDeriveRequest body);


    @Operation(summary = "Get the Hash of a Signed Transaction", description = "TransactionHash returns the network-specific transaction hash for a signed transaction.", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = TransactionIdentifierResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/hash",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<TransactionIdentifierResponse> constructionHash(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionHashRequest body);


    @Operation(summary = "Get Metadata for Transaction Construction", description = "Get any information required to construct a transaction for a specific network. Metadata returned here could be a recent hash to use, an account sequence number, or even arbitrary chain state. The request used when calling this endpoint is created by calling `/construction/preprocess` in an offline environment. You should NEVER assume that the request sent to this endpoint will be created by the caller or populated with any custom parameters. This must occur in `/construction/preprocess`. It is important to clarify that this endpoint should not pre-construct any transactions for the client (this should happen in `/construction/payloads`). This endpoint is left purposely unstructured because of the wide scope of metadata that could be required.", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = ConstructionMetadataResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/metadata",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConstructionMetadataResponse> constructionMetadata(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionMetadataRequest body);


    @Operation(summary = "Parse a Transaction", description = "Parse is called on both unsigned and signed transactions to understand the intent of the formulated transaction. This is run as a sanity check before signing (after `/construction/payloads`) and before broadcast (after `/construction/combine`). ", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = ConstructionParseResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/parse",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConstructionParseResponse> constructionParse(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionParseRequest body);


    @Operation(summary = "Generate an Unsigned Transaction and Signing Payloads", description = "Payloads is called with an array of operations and the response from `/construction/metadata`. It returns an unsigned transaction blob and a collection of payloads that must be signed by particular AccountIdentifiers using a certain SignatureType. The array of operations provided in transaction construction often times can not specify all \"effects\" of a transaction (consider invoked transactions in Ethereum). However, they can deterministically specify the \"intent\" of the transaction, which is sufficient for construction. For this reason, parsing the corresponding transaction in the Data API (when it lands on chain) will contain a superset of whatever operations were provided during construction.", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = ConstructionPayloadsResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/payloads",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConstructionPayloadsResponse> constructionPayloads(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionPayloadsRequest body);


    @Operation(summary = "Create a Request to Fetch Metadata", description = "Preprocess is called prior to `/construction/payloads` to construct a request for any metadata that is needed for transaction construction given (i.e. account nonce). The `options` object returned from this endpoint will be sent to the `/construction/metadata` endpoint UNMODIFIED by the caller (in an offline execution environment). If your Construction API implementation has configuration options, they MUST be specified in the `/construction/preprocess` request (in the `metadata` field).", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = ConstructionPreprocessResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/preprocess",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ConstructionPreprocessResponse> constructionPreprocess(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionPreprocessRequest body);


    @Operation(summary = "Submit a Signed Transaction", description = "Submit a pre-signed transaction to the node. This call should not block on the transaction being included in a block. Rather, it should return immediately with an indication of whether or not the transaction was included in the mempool. The transaction submission response should only return a 200 status if the submitted transaction could be included in the mempool. Otherwise, it should return an error.", tags={ "Construction" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(schema = @Schema(implementation = TransactionIdentifierResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "unexpected error", content = @Content(schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/construction/submit",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<TransactionIdentifierResponse> constructionSubmit(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConstructionSubmitRequest body);

}

